import type { Restaurant, User, Story, Chat } from "@/lib/app-context"

export const restaurants: Restaurant[] = [
  {
    id: "1",
    name: "Red Cream Sweets & Bakery",
    image: "/arabic-sweets-bakery-box.jpg",
    rating: 4.6,
    deliveryTime: "22 mins",
    distance: "5.1 km",
    priceLevel: "$$$",
    categories: ["Cakes", "Chocolate", "Arabic Sweets"],
    isLocal: true,
  },
  {
    id: "2",
    name: "Burger Boutique",
    image: "/gourmet-burger-sesame-bun.jpg",
    rating: 4.5,
    deliveryTime: "25 mins",
    distance: "3 km",
    priceLevel: "$$$",
    categories: ["Fries", "Fast Food", "Burgers", "Fried Chicken"],
    isLocal: true,
  },
  {
    id: "3",
    name: "KFC",
    image: "/fried-chicken-bucket-meal.jpg",
    rating: 4.2,
    deliveryTime: "25 mins",
    distance: "2.5 km",
    priceLevel: "$$",
    categories: ["Fried Chicken", "Fast Food"],
    isLocal: false,
    recommendedBy: ["Ahmed", "Sara"],
  },
  {
    id: "4",
    name: "Captain Shawarma",
    image: "/shawarma-wrap-platter.jpg",
    rating: 4.4,
    deliveryTime: "30 mins",
    distance: "4.2 km",
    priceLevel: "$$",
    categories: ["Shawarma", "Arabic Food"],
    isLocal: true,
    recommendedBy: ["Omar"],
  },
  {
    id: "5",
    name: "Namous",
    image: "/arabic-dessert-kunafa.jpg",
    rating: 4.7,
    deliveryTime: "20 mins",
    distance: "1.8 km",
    priceLevel: "$$",
    categories: ["Desserts", "Arabic Sweets"],
    isLocal: false,
    recommendedBy: ["Sara", "Fatima", "Omar"],
  },
  {
    id: "6",
    name: "Healthy Bowl Co.",
    image: "/healthy-grilled-chicken-salad-bowl.jpg",
    rating: 4.8,
    deliveryTime: "25 mins",
    distance: "2.1 km",
    priceLevel: "$$",
    categories: ["Healthy", "Salads", "High Protein"],
    isLocal: true,
    recommendedBy: ["Dr. Sara"],
  },
  {
    id: "7",
    name: "Fit Burger Lab",
    image: "/lean-beef-burger-with-salad-no-bun.jpg",
    rating: 4.6,
    deliveryTime: "20 mins",
    distance: "1.5 km",
    priceLevel: "$$",
    categories: ["Healthy", "Burgers", "Low Carb"],
    isLocal: true,
    recommendedBy: ["Fahad"],
  },
]

export const friends: User[] = [
  {
    id: "1",
    name: "Ahmed Khalid",
    username: "ahmed_k",
    bio: "Food lover | Exploring Doha's best eats",
    recommendations: 12,
    mutualFriends: 5,
    posts: 24,
    followers: 342,
    following: 156,
    isFollowing: true,
    isVerified: false,
  },
  {
    id: "2",
    name: "Dr. Sara Al-Khater",
    username: "dr.sara.nutrition",
    bio: "Verified Dietitian | Healthy eating advocate | MSc Nutrition",
    recommendations: 8,
    mutualFriends: 3,
    posts: 56,
    followers: 1240,
    following: 89,
    isFollowing: true,
    isVerified: true,
    verificationBadge: "blue",
    verificationTitle: "Verified Dietitian",
  },
  {
    id: "3",
    name: "Omar Hasan",
    username: "chef_omar",
    bio: "Celebrity Chef | TV Host | Restaurant Owner",
    recommendations: 15,
    mutualFriends: 7,
    posts: 189,
    followers: 52000,
    following: 234,
    isFollowing: false,
    isVerified: true,
    verificationBadge: "red",
    verificationTitle: "Public Figure",
  },
  {
    id: "4",
    name: "Fatima Ali",
    username: "fatima_eats",
    bio: "Just here for the desserts",
    recommendations: 6,
    mutualFriends: 2,
    posts: 18,
    followers: 89,
    following: 201,
    isFollowing: true,
    isVerified: false,
  },
  {
    id: "5",
    name: "Youssef Ahmad",
    username: "youssef.qa",
    bio: "Coffee addict | Burger enthusiast",
    recommendations: 10,
    mutualFriends: 4,
    posts: 42,
    followers: 567,
    following: 123,
    isFollowing: false,
    isVerified: false,
  },
  {
    id: "6",
    name: "Fahad FitFood",
    username: "fahad_fitfood",
    bio: "Fitness Coach | Clean Eating | Transform your body",
    recommendations: 22,
    mutualFriends: 8,
    posts: 156,
    followers: 28500,
    following: 312,
    isFollowing: true,
    isVerified: true,
    verificationBadge: "red",
    verificationTitle: "Fitness Influencer",
  },
]

export const recommendations = [
  {
    ...restaurants[0],
    note: "Their baklava is absolutely divine! Perfect for special occasions.",
    recommendedAt: "2h ago",
    recommenderId: "4",
  },
  {
    ...restaurants[1],
    note: "Best gourmet burgers in Doha! The cheese melt is incredible.",
    recommendedAt: "4h ago",
    recommenderId: "5",
  },
  {
    ...restaurants[2],
    note: "Best zinger combo in town, super crispy!",
    recommendedAt: "Yesterday",
    recommenderId: "1",
  },
  {
    ...restaurants[3],
    note: "Authentic shawarma, reminds me of home cooking.",
    recommendedAt: "2 days ago",
    recommenderId: "3",
  },
  {
    ...restaurants[4],
    note: "The kunafa here is incredible, must try!",
    recommendedAt: "3h ago",
    recommenderId: "4",
  },
  {
    ...restaurants[5],
    note: "High-protein grilled option + light sauce. Great post-workout meal.",
    recommendedAt: "1h ago",
    recommenderId: "2",
    tags: ["High Protein", "Low Sugar"],
  },
  {
    ...restaurants[6],
    note: "My go-to clean burger — no fried sides today. Perfect macros!",
    recommendedAt: "5h ago",
    recommenderId: "6",
    tags: ["Low Carb", "High Protein"],
  },
]

export const stories: Story[] = [
  {
    id: "s1",
    userId: "1",
    userName: "Ahmed",
    isNew: true,
    content: {
      type: "recommendation",
      restaurantId: "3",
      restaurantName: "KFC",
      restaurantImage: "/fried-chicken-bucket-meal.jpg",
      restaurantRating: 4.2,
      deliveryTime: "25 mins",
      note: "Best zinger combo in town! Super crispy",
    },
  },
  {
    id: "s2",
    userId: "2",
    userName: "Dr. Sara",
    isNew: true,
    content: {
      type: "recommendation",
      restaurantId: "6",
      restaurantName: "Healthy Bowl Co.",
      restaurantImage: "/healthy-grilled-chicken-bowl-with-vegetables.jpg",
      restaurantRating: 4.8,
      deliveryTime: "25 mins",
      note: "High-protein grilled option + light sauce. Great post-workout meal!",
    },
  },
  {
    id: "s3",
    userId: "3",
    userName: "Omar",
    isNew: false,
    content: {
      type: "recommendation",
      restaurantId: "4",
      restaurantName: "Captain Shawarma",
      restaurantImage: "/shawarma-wrap-platter.jpg",
      restaurantRating: 4.4,
      deliveryTime: "30 mins",
      note: "Authentic shawarma, reminds me of home",
    },
  },
  {
    id: "s4",
    userId: "4",
    userName: "Fatima",
    isNew: true,
    content: {
      type: "recommendation",
      restaurantId: "1",
      restaurantName: "Red Cream Sweets",
      restaurantImage: "/arabic-sweets-bakery-box.jpg",
      restaurantRating: 4.6,
      deliveryTime: "22 mins",
      note: "Their baklava is to die for!",
    },
  },
  {
    id: "s5",
    userId: "5",
    userName: "Youssef",
    isNew: false,
    content: {
      type: "recommendation",
      restaurantId: "2",
      restaurantName: "Burger Boutique",
      restaurantImage: "/gourmet-burger-sesame-bun.jpg",
      restaurantRating: 4.5,
      deliveryTime: "25 mins",
      note: "Best gourmet burgers in Doha!",
    },
  },
  {
    id: "s6",
    userId: "6",
    userName: "Fahad",
    isNew: true,
    content: {
      type: "recommendation",
      restaurantId: "7",
      restaurantName: "Fit Burger Lab",
      restaurantImage: "/lean-beef-burger-with-fresh-salad.jpg",
      restaurantRating: 4.6,
      deliveryTime: "20 mins",
      note: "My go-to clean burger — no fried sides today!",
    },
  },
]

export const getInitialChats = (): Chat[] => [
  {
    id: "c1",
    participants: [friends[0]],
    isGroup: false,
    lastMessage: "Have you tried the new shawarma place?",
    lastMessageTime: "2m ago",
    unreadCount: 2,
    messages: [
      { id: "m1", senderId: "1", content: "Hey! Check out this restaurant", timestamp: "10:30 AM", type: "text" },
      {
        id: "m2",
        senderId: "1",
        content: "",
        timestamp: "10:31 AM",
        type: "shared_post",
        sharedPost: {
          restaurantId: "4",
          restaurantName: "Captain Shawarma",
          restaurantImage: "/shawarma-wrap-platter.jpg",
        },
      },
      { id: "m3", senderId: "me", content: "Looks amazing! Let's go tomorrow", timestamp: "10:35 AM", type: "text" },
      {
        id: "m4",
        senderId: "1",
        content: "Have you tried the new shawarma place?",
        timestamp: "10:40 AM",
        type: "text",
      },
    ],
  },
  {
    id: "c2",
    participants: [friends[2]],
    isGroup: false,
    lastMessage: "The burgers there are incredible",
    lastMessageTime: "1h ago",
    unreadCount: 0,
    messages: [
      { id: "m5", senderId: "3", content: "The burgers there are incredible", timestamp: "9:00 AM", type: "text" },
    ],
  },
  {
    id: "c3",
    participants: [friends[0], friends[1], friends[3], friends[4]],
    isGroup: true,
    groupName: "Foodies Squad",
    lastMessage: "I'm in! Let's order",
    lastMessageTime: "5m ago",
    unreadCount: 8,
    messages: [
      {
        id: "fg1",
        senderId: "1",
        content: "Hey everyone! Where should we order tonight?",
        timestamp: "6:00 PM",
        type: "text",
      },
      { id: "fg2", senderId: "4", content: "I'm craving something good", timestamp: "6:02 PM", type: "text" },
      { id: "fg3", senderId: "5", content: "Check this gem", timestamp: "6:03 PM", type: "text" },
      {
        id: "fg4",
        senderId: "5",
        content: "",
        timestamp: "6:03 PM",
        type: "shared_post",
        sharedPost: {
          restaurantId: "2",
          restaurantName: "Burger Boutique",
          restaurantImage: "/gourmet-burger-sesame-bun.jpg",
        },
      },
      { id: "fg5", senderId: "4", content: "That looks insane!", timestamp: "6:05 PM", type: "text" },
      { id: "fg6", senderId: "1", content: "Omg yes! Best burgers in Doha", timestamp: "6:06 PM", type: "text" },
      {
        id: "fg7",
        senderId: "2",
        content: "I'm trying to eat clean this week actually",
        timestamp: "6:08 PM",
        type: "text",
      },
      {
        id: "fg8",
        senderId: "2",
        content: "Dr. Sara recommended a high-protein bowl",
        timestamp: "6:08 PM",
        type: "text",
      },
      {
        id: "fg9",
        senderId: "2",
        content: "",
        timestamp: "6:09 PM",
        type: "shared_post",
        sharedPost: {
          restaurantId: "6",
          restaurantName: "Healthy Bowl Co.",
          restaurantImage: "/healthy-grilled-chicken-salad-bowl.jpg",
        },
      },
      { id: "fg10", senderId: "5", content: "That actually looks really good", timestamp: "6:11 PM", type: "text" },
      { id: "fg11", senderId: "4", content: "Can we do both?", timestamp: "6:12 PM", type: "text" },
      {
        id: "fg12",
        senderId: "1",
        content: "Let's do that + one burger option for sharing",
        timestamp: "6:14 PM",
        type: "text",
      },
      {
        id: "fg13",
        senderId: "2",
        content: "Perfect! I'll order the healthy bowl",
        timestamp: "6:15 PM",
        type: "text",
      },
      {
        id: "fg14",
        senderId: "5",
        content: "Anyone tried the new shawarma place?",
        timestamp: "6:17 PM",
        type: "text",
      },
      {
        id: "fg15",
        senderId: "1",
        content: "",
        timestamp: "6:18 PM",
        type: "shared_post",
        sharedPost: {
          restaurantId: "4",
          restaurantName: "Captain Shawarma",
          restaurantImage: "/shawarma-wrap-platter.jpg",
        },
      },
      {
        id: "fg16",
        senderId: "1",
        content: "This one is amazing, Omar recommended it",
        timestamp: "6:18 PM",
        type: "text",
      },
      { id: "fg17", senderId: "4", content: "Okay now I'm really hungry", timestamp: "6:20 PM", type: "text" },
      { id: "fg18", senderId: "5", content: "Order now? I'll get the burger", timestamp: "6:21 PM", type: "text" },
      {
        id: "fg19",
        senderId: "2",
        content: "I'll order the bowl, we all get SnooCoins!",
        timestamp: "6:22 PM",
        type: "text",
      },
      { id: "fg20", senderId: "4", content: "I'm in! Let's order", timestamp: "6:23 PM", type: "text" },
    ],
  },
  {
    id: "c4",
    participants: [friends[4]],
    isGroup: false,
    lastMessage: "Thanks for the recommendation!",
    lastMessageTime: "Yesterday",
    unreadCount: 0,
    messages: [
      { id: "m8", senderId: "5", content: "Thanks for the recommendation!", timestamp: "Yesterday", type: "text" },
    ],
  },
]

export const chats: Chat[] = getInitialChats()
